apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-kustomize
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/base
    repoURL: 'https://github.com/toplordsaito/helm-devops-tools'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
